---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        extraArgs:
          - "--log.level=debug"
