dbt_duckdb_s3_project:
  target: dev
  outputs:
    aws:
      type: duckdb
      path: dbt.duckdb
      extensions:
        - parquet
        - httpfs
        - aws
      use_credential_provider: aws
      settings:
        threads: 1
        memory_limit: 512MB
        s3_region: "eu-central-1"
      external_root: s3://de-research/data/dbt_duckdb/processed

    dev-docker:
      type: duckdb
      path: dbt.duckdb
      settings:
        threads: 1
        memory_limit: 512MB
      external_root: ../data/processed

    dev:
      type: duckdb
      path: dbt.duckdb
      external_root: ../data/processed

    dpe:
      type: duckdb
      path: ../data/dpe.duckdb
