argo-cd-project-create:
	argocd proj create dev --file projects/dev.yaml
argo-cd-project-delete:
	argocd proj delete dev
argo-cd-project-list:
	argocd proj list

argo-cd-app-create:
	argocd app create xxx --file=xxx.yaml
argo-cd-app-sync:
	argocd app sync xxx
