apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    name: in-cluster
  project: default
  source:
    path: kubernetes/apps  # contains application spec files
    repoURL: https://github.com/akv-akv/de_research.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true