[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "3.12.x"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.8.0"
black = "^24.8.0"
isort = "^5.13.2"
dbt-postgres = "^1.8.2"
