akv_dbt_project:
  target: dev
  outputs:
    aws:
      type: duckdb
      extensions:
        - httpfs
        - parquet
      filesystems:
        - fs: s3
      external_root: s3://de_research/dbt_duckdb/

    dev:
      type: duckdb
      external_root: ../data/processed

    dpe:
      type: duckdb
      path: ../data/dpe.duckdb
