apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
spec:
  description: Applications General Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: apps
    server: https://kubernetes.default.svc
  - namespace: argocd
    server: https://kubernetes.default.svc
